### ISSUE TITLE
give each woofjs.com project a number of cloud variables in firebase

### ISSUE THREAD

**Issue by stevekrouse** [stevekrouse/WoofJS#224]
need to think about:
- what kinds of things they can store (data structures and sanitiization)
- how we limit the number of things they store to a reasonable amount
- if we can protect their variables from hacking in some way

**Comment by hallpell** [comment]
We're likely just leaving Firebase as something students can integrate with their own projects when needed, but not handling any of this for them. This unfortunately makes it a bit less accessible
