### ISSUE TITLE
remove all imgur and postimage links in coding.space and woofjs.com

### ISSUE THREAD

**Issue by stevekrouse** [stevekrouse/WoofJS#261]

**Comment by stevekrouse** [comment]
The best way to make sure you get all of them is to do a directory-level search for "postimage" and "imgur". You can do this in cloud9 by clicking on the WoofJS directory and then hitting SHIFT+CTL+F

**Comment by stevekrouse** [comment]
There are `images/` folders scattered throughout the project to house the image files for that level of the project for example, there's `WoofJS/images`, and there's `WoofJS/docs/images`. The idea is to transfer the postimage and imgur links to those directories.

There's a special terminal command that can help you with this.

If you change directory to the releveant image directory, for example `cd WoofJS/docs/images` you can then do `wget https://imgur.com/IMAGEURL.jpg` and it will download the image to that directory.

Then back in the HTML code that references that image, you have to change it from the imgur link to the new link in the images folder.

**Comment by madduccino** [comment]
Got it. Thanks!
