### ISSUE TITLE
call to action on the homepage / better onboarding flow / better user conversion

### ISSUE THREAD

**Issue by stevekrouse** [stevekrouse/WoofJS#273]

**Comment by nicolekelner** [comment]
https://www.intercom.com/customer-engagement
It could be cool to use Intercom to onboard users. You can walk them through the steps on creating their first project, like viewing the tutorials button, clicking first project, building their first game, and saving their project! 

It has a 2 week free trial but then it is a pay per user service, so it could be nice to test for 2 weeks!

**Comment by nicolekelner** [comment]
A free more controllable option would be to use http://introjs.com/. We can code the tutorial and provide an option to use it instead of a popup!

**Comment by stevekrouse** [comment]
I want to rethink the flow of a new person landing on woofjs.com. While fun, I don't think the homepage we have now with the typing intro demo is the right message for everyone.

I want to think about the funnel and how we can optomize each step of it. 

**New students who want to try out Woof**

Possible call to actions: play in the editor, create an account, view other students' projects, save a project.

What is the goal here? Probably creating an account or saving a project, yes?

**New teachers who are curious to learn more about Woof**

Possible call to actions: play in the editor, create an account, view other students' projects, save a project, view the teacher guide, email us, schedule a time to meet with us

What's the goal here? Signing their students up for Woof? Doing a number of Woof projects themselves?

I think it'd be fun to make a project out of this, maybe copying someone like Slack that we admire here.
