### ISSUE TITLE
better errors for bad image urls

### ISSUE THREAD

**Issue by stevekrouse** [stevekrouse/WoofJS#274]

**Comment by nicolekelner** [comment]
I think this should be closed, I took care of it in a different pull request!

**Comment by stevekrouse** [comment]
Of course. In the future, feel free to go ahead and close issues that you resolved by yourself. Let me know if you don't have access to do that.

If you want to be extra considerate, you can link to the pull request that fixed the issue (in this case https://github.com/stevekrouse/WoofJS/pull/334) so there's no ambiguity. That's really a best practice but sometimes I'm lazy about it.
