### ISSUE TITLE
copy features from three js's editor

### ISSUE THREAD

**Issue by stevekrouse** [stevekrouse/WoofJS#278]

**Comment by stevekrouse** [comment]
This issue is as simple as looking at the following URL and creating more WoofJS issues based on the features from their editor we might want to copy.

https://threejs.org/editor/

**Comment by stevekrouse** [comment]
Another good place to copy from is tynker.com

**Comment by dilsheen** [comment]
This would be my first contribution on GitHub but this seems like a good first project to contribute to.  I have read the above but am still slightly confused. Can you help me?

**Comment by stevekrouse** [comment]
Hi @dilsheen - thanks for reaching out! I see your confusion - this issue may be improperly labeled as a "good first issue." May I suggest a better place to start? Maybe try one of these:

https://github.com/stevekrouse/WoofJS/issues/465
https://github.com/stevekrouse/WoofJS/issues/316
https://github.com/stevekrouse/WoofJS/issues/433
