### ISSUE TITLE
save photos of projects on save

### ISSUE THREAD

**Issue by stevekrouse** [stevekrouse/WoofJS#284]
There are two things that need to happen here:

1) We need to "take a picture" of the canvas when the user hits "Save"
2) We need to upload this picture somewhere and associate a link to that picture in the database for this project

The tricky part about (1) is that we have a canvas for sprites, for the pen, and for the background so we will somehow how to put all those together for this picture. It seems like it isn't that hard to turn a canvas into an image so the real trick will be combining it with the background image.

**Comment by jwass91** [comment]
This might be of help https://screenshotlayer.com/

**Comment by stevekrouse** [comment]
Great find! We could ask them to take a screenshot of the project in full screen mode for us. It's cool that they have the ability to tell them to wait a bit after the pages loads before taking the picture -- I think that would come in handy.

What I was imagining is similar to how Scratch does it. It takes a "screenshot" of the game on the /create.html page when you hit the save button. This way you can really customize what the screenshot looks like by getting the state of your game to that place. 

That said, this might be super hard so I'm fine to go with this service (or a similar one) for now. Feel free to create an account with it and try it out!

**Comment by stevekrouse** [comment]
Closed https://github.com/stevekrouse/WoofJS/pull/496
