### ISSUE TITLE
better hint when copying documentation code and forgetting to change sprite name

### ISSUE THREAD

**Issue by stevekrouse** [stevekrouse/WoofJS#299]
A common mistake (even for advanced users) is that they'll grab an image sprite, like pikachu, and then drag, sprite1.move(10) and be confused when it doesn't work.

The coolest thing would be to ask the user as they drag certain blocks, "which sprite is this block for?" and then add the name automatically.

Less cool but easier to do would be to add a warning or error message next to the line number in the text editor gutter that suggests that they rename the variable.

**Comment by nicolekelner** [comment]
So it seems like everything that controls what a woof command does has been defined in woof.es6.js and there are a lot of error messages created there. But I don't specifically see  "sprite1" ever there. I know that the error that comes up right now if you type in sprite1.move(10) is sprite1 is undefined. Basically I was trying to make it if the console receives sprite1 is undefined then create an alert message with an input box to change your sprite1 to the name of the variable you want to move


I was trying to create a function that is essentially- if (sprite1 is not defined) then (throw error alert)

**Comment by stevekrouse** [comment]
I like the idea of a `prompt()` asking the user to rename sprite1 to the name of their sprite.

This is where you'd want to put that if... https://github.com/stevekrouse/WoofJS/blob/2284cbae40bd286dc352df3fa88f69e44211c621/create.html#L623
