### ISSUE TITLE
make javascript control flow (particularly with repeats) more clear

### ISSUE THREAD

**Issue by stevekrouse** [stevekrouse/WoofJS#306]
https://github.com/stevekrouse/WoofJS/tree/0856733d21df9f7be57cc3dac547a1ea208523fd#control-flow

**Comment by stevekrouse** [comment]
Instead of `repeat(10, () => {}, () => {})` we could have `repeat(10, () => {}).then(() => {})`. Ditto for repeatUntils.

One (probably bad) idea is that instead of` after(1, "second", () => {})`, we could have `wait(1, "second").then(() => {})`. That might confuse people into thinking that waits work the same here as they do in JavaScript and leave off the then.

**Comment by stevekrouse** [comment]
We definitely need to make this more clear that repeats are doing strange asynchronous things and that there's this strange third parameter callback thing. Or change the API to return a promise that you can call .then on.

Samantha John of Hopscotch:

> Can I report a bug in woofjs? http://woofjs.com/create.html#grid-fail I thought this would make a grid, but it doesn't! The console output is crazy. I assume there is some sort of parallelism going on that makes the order a bit non-deterministic. 

Here's one way around this problem -- don't use repeat but use synchronous loop:  http://woofjs.com/create.html#grid-fail-1

However, if you want the grid creation to happen in an animated way, things become really complicated. You may need to use recursion... Here's how you can do it for a fixed number of iterations, like drawing a square:

```javascript
repeat(100, () => {
  NAME.angle = RIGHT;
  NAME.move(1);
}, () => { 
  repeat(100, () => {
    NAME.angle = UP;
    NAME.move(1);
  }, () => { 
    repeat(100, () => {
      NAME.angle = LEFT;
      NAME.move(1);
    }, () => { 
      repeat(100, () => {
        NAME.angle = DOWN;
        NAME.move(1);
      });
    });
  });
});
```

**Comment by samjohn** [comment]
I expected repeat to be synchronous. From Websters: "to do or say what one has already done". There is an implication that you can't repeat something until you've finished it.

**Comment by stevekrouse** [comment]
To be clear, @samjohn, `repeat` is synchronous in that it does each cycle inside itself one after another, once each render cycle. So a single `repeat` command would act like you expect. Where things get tricky is that `repeat` commands don't block the execution of the program (because JavaScript doesn't really make that easy -- potentially we can use the aync keyword but I haven't totally figured out how that might work). So when you nested a `repeat` inside a `repeat`, it began the second repeat before the first repeat finished.

So I think we need to make it more clear, potentially by changing the name of functions, so that it's more clear that `repeat` is animating (and not waiting until it's completed before moving to the next line) and `range.forEach` is going as fast as the computer can and blocking until done. Potentially we could remove the repeat command altogether and replace it with this syntax:

```javascript
var times = 10
forever(() => {
  if (times > 0) {
    // do something
   times = times - 1
  }
})
```

**Comment by samjohn** [comment]
maybe you could do repeat in a blocking way rather than with callbacks? Tried it in scratch and it worked. https://scratch.mit.edu/projects/171587475/

**Comment by stevekrouse** [comment]
Great, point @samjohn! That's definitely the most intuitive way to go. Here are the options as I see them:

1. Delete the `repeat` keyword entirely. [Use `range().forEach()` for fast repeat](http://woofjs.com/create.html#grid-fail-1) and [a forever with an iterator for animated repeat](http://woofjs.com/create.html#repeat-with-forever). 

```javascript
range(-4, 4).forEach(column => {
  range(-4,4).forEach(row => {
    new Rectangle({
      width: 55,
      height: 55,
      color: "tomato",
      x: 60 * column,
      y: 60 * row
    });
  })
})
```

2. Change the behavior of `repeat` to be synchronous. (So it's like a more intuitive version of `range().forEach()` -- they'd do the same thing but with a less expressive iterator.) The student could use [a forever with an iterator for an animated repeat](http://woofjs.com/create.html#repeat-with-forever).

```javascript
// example of how a synchronous repeat would create a grid
// @samjohn's original code would've worked:
var column = -4
var row = -4
repeat(8, () => {
  repeat(8, () => {
    new Rectangle({
      width: 55,
      height: 55,
      color: "tomato",
      x: 60 * column,
      y: 60 * row
    });
    row = row + 1;
  })
  column = column + 1;
  row = -4
})
```

3. Attempt to mirror Scratch's semantics 100% like @samjohn suggests above. [Change the behavior of `repeat` to evaluate it's functions sequentially, awaiting for each one to finish before moving to the next, but keeping the animating nature of repeat .](http://woofjs.com/create#square-promises). While this solution is elegant, the downside is that you have to litter you code with `await` and `async` keywords. I worry that these strange new keywords and the concepts about promises that go along with them would be more confusing than they're worth. (Personally, I found it impossible to get this code to work without first deeply understanding promises, but I wonder if there's a way around that.) On the other hand, these keywords are the future of JavaScript and there's something to be said for teaching them to students.

```javascript
(async () => { 
  var column = -4
  var row = -4
  await repeat(8, async() => {
    await repeat(8, async() => {
      new Rectangle({
        width: 55,
        height: 55,
        color: "blue",
        x: 60 * column,
        y: 60 * row
      });
      row = row + 1;
    })
    column = column + 1;
    row = -4
  })
})()  // the await keyword only works inside async functions, which is why we define one and call it here
```

**Comment by samjohn** [comment]
If I understand correctly option 2 means that each loop will happen on the main thread and block execution of other code (including code from other characters). Option 3 means that the repeats will still happen on their own thread but will wait for the previous loop to return before executing. 

I think the best option depends on what kind of defaults you want to establish for woof. Is code synchronous or asynchronous by default? How should kids think about sequential code? For example, should they expect line 2 to always execute after line 3?

Another thing to consider is the goals of woof. I would only use the await/async keywords if the goal is to teach kids the javascript language. Otherwise I'm sure you can make a better syntax than that to accomplish whichever option that you decide on.

**Comment by stevekrouse** [comment]
Good questions! 

> Is code synchronous or asynchronous by default? How should kids think about sequential code? For example, should they expect line 2 to always execute after line 3?

I think it depends. Like all JavaScript code, some code is synchronous and some is asynchronous. Students don't really think about it, but even something as simple as putting code below a `forever` loop makes it clear that code isn't truly synchronous. This is a really tricky concept to wrap your head around. Scratch makes it really easy with it's architecture, but that's hard for us to mimic here for a number of reasons.

> Another thing to consider is the goals of woof. 

This is a great question! The goal of Woof is to be the "next step after Scratch." Currently Woof is a JavaScript framework, but the goal definitely isn't to "teach JavaScript." Part of why I think it's important that Woof is truly JavaScript (and not a custom language) is that students would be less excited to learn it after Scratch if it's just another not-real-programming-language-for-kids.

> I would only use the await/async keywords if the goal is to teach kids the javascript language. Otherwise I'm sure you can make a better syntax than that to accomplish whichever option that you decide on.

When you suggest making a better syntax, are you suggesting that Woof shouldn't be a JavaScript framework anymore -- that we should build a custom syntax for it? I'm not sure how else to create a better syntax to accomplish that particular option -- do you? There aren't native macros in JavaScript (sadly) so there aren't ways to design custom control flow that I know of.

@joebeachjoebeach @ekenberg @madduccino @nicolekelner  and @seg2176  - I'd appreciate your thoughts here if you have anything to add :)

**Comment by joebeachjoebeach** [comment]
This is definitely a tricky issue. Obviously the most desirable solution is one in which @samjohn's original code works. It's intuitive, and it makes sense. But it's looking like it might not be achievable.

As far as using `async` functions goes, I've been exposed to them and I understand how they work, but not having used them myself much, I'm not sure how meaningful my $0.02 would be. It would be great if we could somehow "hide" that syntax from the user, but a cursory glance makes me think that wouldn't be possible.

In terms of Woof being the "next step after Scratch," the async/await option gets +2 points for mirroring Scratch's semantics but -3 points for being confusing for a novice programmer.

Woof does already have instances of "Scratch has this, but we don't. Here's how to do it in Woof," so maybe suggesting forever + iterator wouldn't be the worst thing.

I really like the idea of having `repeat()` return a promise that we can call `.then()` on. I think this would be a big step forward in terms of improving intuitiveness. @stevekrouse, when you say "That might confuse people into thinking that waits work the same here as they do in JavaScript," do you mean people may confuse Woof's `wait()` with `await`? Or is there something I'm missing? I do like the idea of moving from `after(1, 'second', () => {})` to `wait(1, 'second').then(() => {})`

**Comment by stevekrouse** [comment]
Good thoughts, @joebeachjoebeach. My gut is to remove `repeat` and `repeatUntil` keywords entirely and show how to do them with `forever`s or `range().forEach()`.

To clarify what I meant [here](https://github.com/stevekrouse/WoofJS/issues/306#issuecomment-304543178)... I was saying that making` repeat` and `repeatUntils` return promises that you can call `then` on sounds like a good idea instead of a third parameter. 

However, doing the same thing for `wait` could be confusing. I could see students thinking that the following code might work:

```javascript
wait(1, "second).then(() => {})
// put code here below the wait() instead of inside the then() and expect this to happen 1 second later
```

After makes the semantics a little more clear. So `wait` is plus 1 point for similarity to JS but minus 1 point for this opportunity for confusion.

**Comment by samjohn** [comment]
I had another thought: 
You could make code outside of a `repeat` block async (so `repeat forever` doesn't block code around it). 
But within a `repeat` the code is synchronous, each line has an implicit `await`.

I *think* that would solve my problem, because you'd have to wait for the inner `repeat` to finish before going to the next loop. But it still wouldn't break the existing `repeat forever` functionality. 

I don't know woof well enough to know if that would break a bunch of other things but it could be pretty elegant.  

You could also add an `async` keyword in case you didn't want the `repeat` to be synchronous. Or have an `async repeat` block. I am not actually sure what the use case would be for the code inside the repeat to be non-sequential though.

**Comment by stevekrouse** [comment]
Interesting idea @samjohn! I do like the elegance of it.

Haven't totally thought it through but some thoughts that immediately come to mind:

1. We'd need to transpile that code to JS, which would make WoofJS no longer a JS framework but a JS-like langauge. I'm not entirely against that but it's a big decision. We could potentially use something like https://www.sweetjs.org/

2. I don't think this would solve all problems with repeats because sometimes kids will want to sequence repeats, for example drawing a square, which currently you have to do like this:

```javascript
repeat(100, () => {
  NAME.angle = RIGHT;
  NAME.move(1);
}, () => { 
  repeat(100, () => {
    NAME.angle = UP;
    NAME.move(1);
  }, () => { 
    repeat(100, () => {
      NAME.angle = LEFT;
      NAME.move(1);
    }, () => { 
      repeat(100, () => {
        NAME.angle = DOWN;
        NAME.move(1);
      });
    });
  });
});
```

Which we could make slightly better with `then`s:

```javascript
repeat(100, () => {
  NAME.angle = RIGHT;
  NAME.move(1);
}).then(() => { 
  repeat(100, () => {
    NAME.angle = UP;
    NAME.move(1);
  }).then(() => { 
    repeat(100, () => {
      NAME.angle = LEFT;
      NAME.move(1);
    }).then(() => { 
      repeat(100, () => {
        NAME.angle = DOWN;
        NAME.move(1);
      });
    });
  });
});
```

My gut says that getting rid of repeats entirely and encouraging students to do this with a forever might be cleanest.

```javascript
var steps = 1
forever(() => {
  if (steps <= 100) {
  NAME.angle = RIGHT;
  NAME.move(1);
  } else if (steps <= 200) {
    NAME.angle = UP;
    NAME.move(1);
  }
  else if (steps <= 300) {
    NAME.angle = LEFT;
    NAME.move(1);
  }
  else if (steps <= 400 {
    NAME.angle = DOWN;
    NAME.move(1);
  }
  steps++
})

**Comment by joebeachjoebeach** [comment]
Those suggestions sound good to me, @stevekrouse

**Comment by stevekrouse** [comment]
Potentially this way with promises could be good: https://woofjs.com/create#repeats-promises

**Comment by hallpell** [comment]
This is an interesting discussion, but I think where Woof has landed has it unlikely to wander away from the event-focused style that JavaScript is built around. Adding in promise-based loops is a possible addition, but unlikely to happen in the near future. It's mainly that most functionality is possible to implement in some way currently, and adding a secondary way to implement loops is likely to cause some confusion in students asking "which way is better".

The other interesting thing that caught my eye in this thread is "the goal of WoofJS isn't to teach JavaScript", where I'm not sure I agree with that at this point in time. The primary goal is still to be a next step past Scratch, but I think teaching JavaScript is a substantial goal.
