### ISSUE TITLE
add get/post ajax external requests to woof

### ISSUE THREAD

**Issue by stevekrouse** [stevekrouse/WoofJS#320]
I think it makes sense to include ajax helpers directly into the `src/woofjs.es6.js` file. The alternative is to require students include it in separately as a library (which is still pretty rough on woofjs.com). Anyways, ajax requests are pretty much built into JS already -- we're just providing a helper or two to make the syntax slightly easier.

 Possible names: `get()`, `getData()`, `getJSON()`, `getDataFromURL()`, ...

I imagine it would take a URL and a callback that it supplies the payload to.

For a project of my own, I followed the advice of this post http://andrewhfarmer.com/ajax-libraries/... and used `fetch()` and it was awful for reasons I don't remember. I've only had positive experiences with JQuery AJAX so I'd use that as inspiration, although my bet is that their solution is more involved than we need so we can probably write a simpler version on our own.

**Comment by stevekrouse** [comment]
Once we complete this issue, we can then add an issue to github.com/stevekrouse/coding.space to create curriculum that pulls data from AJAX sources like https://github.com/jdorfman/awesome-json-datasets

Like a weather app, for example

**Comment by stevekrouse** [comment]
https://stackoverflow.com/questions/6132796/how-to-make-a-jsonp-request-from-javascript-without-jquery

**Comment by stevekrouse** [comment]
Here's a first stab at what the `getData()` function could look like: http://woofjs.com/create.html#weather

@joebeachjoebeach - could I get some feedback on this?

Some things that I'm worried about:

* URL's we're grabbing data from will be long so it might make sense to put them in a separate variable like I did above so you can better see the callback. That might be complicating things though.
* Do we like creating the text sprite outside the data request with `"..."` as the initial value or should we just create the text sprite inside the data request so doesn't exist until the data loads?
* It's difficult (even for me) to pull the relevant data out of a nested javascript object. I can really only do it with a JSON viewer chrome extension. Is this a show stopper? Should we link students to a JSON viewer like http://www.jsoneditoronline.org/? Will we eventually want to build some sort of JSON viewer within woofjs?

**Comment by stevekrouse** [comment]
fyi @joebeachjoebeach -- @jwass91 has been working on this a bit in conjunction with #389 Integrations. Can you let us know if you have plans to continue working on this or would like @jwass91 to take it over?

**Comment by stevekrouse** [comment]
We should link to https://joebeachjoebeach.github.io/json-path-finder/ in the documentation so that students can find the path to the date they are looking to

**Comment by joebeachjoebeach** [comment]
@jwass91 go ahead!
