### ISSUE TITLE
textAlign is confusing

### ISSUE THREAD

**Issue by stevekrouse** [stevekrouse/WoofJS#325]
When you set `textAlign: "left"`, the text moves to the right, and vice-versa. It makes sense why this happens as you can see in this diagram: https://www.w3schools.com/tags/canvas_textalign.asp

In other words, `textAlign: "left"` means that the the left edge of the text is lined up with where you specified `x` and `y`. This allows you to say `x: minX + 10` and `textAlign: "left"` and you can be assured that the text will start at the left side of the screen and go to the right. 

Maybe we should add another way to set it, like "end" or "start" (these are already options built into the canvas so we'd just have to add them to the documentation). Can someone come up with more clear ways to set this?

**Comment by stevekrouse** [comment]
I think a simple solution would be embedding the picture I link to above somewhere in the text sprite documentation:

![image](https://cloud.githubusercontent.com/assets/2288939/26743289/404fb4ae-47af-11e7-8906-2bff3dab5666.png)

**Comment by stevekrouse** [comment]
@Anshuman-Verma want to take this one?

**Comment by Anshuman-Verma** [comment]
Sure @stevekrouse  thanks for the mention , was working on building is fundamentals . 😄

**Comment by Anshuman-Verma** [comment]
Assign me this , I'll get it done

**Comment by stevekrouse** [comment]
Hey @Anshuman-Verma - I don't think I can assign you to issues so I'll tag you in the comments when I want to ask for you help :)
