### ISSUE TITLE
add package.json

### ISSUE THREAD

**Issue by stevekrouse** [stevekrouse/WoofJS#326]
We currently don't have a `package.json` file in woof. Because of this, we actually end up asking developers to create one in the readme with `npm init --yes` and then install babel manually.

Instead of this, we should have a `package.json` file in woof so they don't have to init npm. Then can just say `npm install` or whatever the command is and it will automatically go grab babel.

**Comment by stevekrouse** [comment]
Hopefully this would also include a command to run the tests. 

And a command to compile all the files. In theory this would allow us to slowly add a more robust build system to the project although I do like how simple things are now.

**Comment by stevekrouse** [comment]
We could also add a `.gitignore`

**Comment by joebeachjoebeach** [comment]
I came to post this idea as a new issue myself, and lo and behold, it's been here all along.

It would really streamline the development process, and allow new contributors to get up and running more quickly. I'm happy to take it on.

In terms of adding to the build system, we could use <a href="https://www.npmjs.com/package/prettier" target="_blank">prettier</a> to standardize code formatting, which would eliminate the need for code revisions/edits just for formatting.

**Comment by stevekrouse** [comment]
Agreed! This is also somewhat related to #328. 

I'd love the idea of having prettier standardize code formatting. Give it a shot and see what happens. I imagine this would be a pretty big pull request because you'd be reformatting every line of every file.

**Comment by joebeachjoebeach** [comment]
Cool! I'm excited about this.

Do you have any adjustments you'd like to make to the [default prettier rules](https://github.com/prettier/prettier#options)?

**Comment by stevekrouse** [comment]
I wonder if we can somehow integrate it into c9...

I think you'll have to play with the print width.

Semicolons should be set to false.

Trailing commas "es5"

Bracket spacing false

**Comment by joebeachjoebeach** [comment]
I'll look into c9 integration. I personally have decided to stop using c9 for Woof development because it's been unreliable for me for whatever reason, so I'd like to have an environment-agnostic solution.

Another suggestion for further down the road: what would you think of breaking the codebase into modules and compiling with Webpack? We could break things up into something like `main/`, `sprites/`, `control/`, `math/`, and `helpers/`. The Webpack compiling could be bundled in with whatever npm script we use for Babel compiling. Would this be worth the effort or is it needlessly complicating things?

**Comment by stevekrouse** [comment]
In my experience webpack and other build tools are a pain in the ass. I really like how dead simple the WoofJS build experience is: basically none. 

Of course the downside is large monolithic files that aren't minified in any way. I bet we could use a smart build setup to drastically reduce our file size and thus load time. I'd be curious to know what kind of improvements there are to be made here -- definitely a worthwhile research project eventually.

You're more than free to give it a whirl, but I'm definitely skeptical.
