### ISSUE TITLE
have a button to display the x-y axis on woof

### ISSUE THREAD

**Issue by stevekrouse** [stevekrouse/WoofJS#327]
Tynker has a button that optionally overlays the x-y axis on the output. It also tells you the x-y of your mouse position. I think this would be a great addition to woof!

![screenshot 2017-03-08 at 11 10 35 am](https://cloud.githubusercontent.com/assets/2288939/23712633/7ecbb13a-03f1-11e7-92b6-47abc12200f3.png)

**Comment by nicolekelner** [comment]
I know we had a version of woof with X and Y programmed. Where could I find that to reference?

**Comment by stevekrouse** [comment]
You may be thinking about when we had a `debug` keyword that made it easy to put variables on the screen. I think early versions of woofjs.com had `debug` statements for `mouseX` and `mouseY` included in the code by default. You could mimic that now with `Text` sprites.

However, this issue is to create a button that does this, not sprites. I think that's much cleaner. Potentially, we could just put the `mouseX` and `mouseY` numbers in the top bar over preview with no button...

Also, it would be cool if we could have `maxX` `maxY` `minX` `minY` someone explained through this as well. Maybe when your mouse is at those numbers, it could have `maxX` in parenthesis next to it's value
