### ISSUE TITLE
backdrop canvas div width=0, height=0 in jsbin, jsfiddle but not woofjs.com/create

### ISSUE THREAD

**Issue by stevekrouse** [stevekrouse/WoofJS#338]

**Comment by stevekrouse** [comment]
This is where we set the width and height of the backdrop canvas div: https://github.com/stevekrouse/WoofJS/blob/master/src/woof.es6.js#L125

And this is where we get the width and height of the screen for fullscreen: https://github.com/stevekrouse/WoofJS/blob/master/src/woof.es6.js#L72

However when I debugged this by setting breakpoints, it seems liked this code was running properly. I have a strange feeling that this is a weird bug.

One difference between JSbin and Woof is that in woof we synthetically trigger a 'load' event so that woof thinks the page is being loaded. To be honest, I forget exactly why we do this but that might be part of it... https://github.com/stevekrouse/WoofJS/blob/master/create.html#L625

**Comment by madduccino** [comment]
Here's where it broke: https://github.com/stevekrouse/WoofJS/commit/1e9b9a5e25ec87307efbe17924a09c4e0865fe6e

How would I go from here again?

**Comment by stevekrouse** [comment]
Ah, that makes sense!

Sometimes, a woof developer forgets to commit the new compiled core library after they make changes to it. Their changes don't come into the core library until the next developer to edit the core library compiles it. That's what happened here.

So it looks like the bug came from this pull request: https://github.com/stevekrouse/WoofJS/pull/276

That's a long time ago! But it makes sense. That pull request totally changed the way we render backdrops.

Moving on... the most pressing question in my mind is: why does this work on woofjs.com/create and not on jsbin or jsfiddle? It feels important to understand that before we move on. My suspicion is that it has something to do with how to set the CSS of the iframe on /create.

You could try to reproduce this bug on cloud 9 by creating an HTML page, including Woof, and previewing it. I'd be curious if the bug shows up there. 

Let me know if you'd like more debugging ideas! This is a hard one so at the very least you'll get to see how my mind works when I'm debugging.

**Comment by madduccino** [comment]
If you change "div" back to "canvas" on this line, the bug is resolved: 

https://github.com/stevekrouse/WoofJS/blob/master/src/woof.es6.js#L122

Also, if you remove the Doctype declaration, the bug doesn't happen either.

So it has something to do with how the DOM is treating canvas vs div.

This makes the background blue:

<canvas id="backdrop" width="269" height="567" style="z-index: 1; position: absolute; background:  0% 0% / 100% 100% no-repeat blue;"></canvas>

This doesn't:

<div id="backdrop" style="z-index: 1; position: absolute; background:  0% 0% / 100% 100% no-repeat blue;"></div>

**Comment by stevekrouse** [comment]
Very interesting! Great investigative work, @madduccino!

I noticed that in the examples you pasted above, the `canvas` has its `width` and `height` HTML attributes set but the `div` does not. Those should be set in [this line](https://github.com/stevekrouse/WoofJS/blob/master/src/woof.es6.js#L125) and the one below. However, I am realizing that we might have to set the `width` and `height` of a `div` by setting it's CSS though the style property as opposed to directly on the HTML element, as we do [here](https://github.com/stevekrouse/WoofJS/blob/master/src/woof.es6.js#L163) and on the line below. Let me know if that resolves anything.

The doctype thing is very interesting! That is probably the reason it works on `/create` and not on JSbin and JSFiddle, because those sites include the doctype and `/create` does not. (I believe that JSBin and JSFiddle also work by previewing the page in its own iframe, so that's not entirely it.) So it seems like this was a bug that we should've discovered immediately but that because we don't include the doctype, we didn't realize it for some reason. Potentially we should include the doctype in the `/create` iframe so that this doesn't happen in the future. (We should also confirm that if we add the doctype to the `/create` iframe that it reproduces the bug.)
