### ISSUE TITLE
code section block comment

### ISSUE THREAD

**Issue by stevekrouse** [stevekrouse/WoofJS#350]
We have students that are creating Woof projects of thousands of lines, like [this one](http://woofjs.com/create.html#wildiaxfirst). Woohoo!

In order to make these projects more readable and easy to find things, we should give students a template for code section block comments like the following in the Woof documentation to copy and paste:

```javascript
// ----------------------------------------------------------
// ------------ Instruction Screen Sprites ------------------
// ----------------------------------------------------------
```

**Comment by Anshuman-Verma** [comment]
I'll start working on the issue, just tell me the exact details of what is to be done and i'll have it all fixed one by one. 
Do we need comment block for each element in the Documentation block ? Should they be embedded along with the code or should be present outside the code block (for convenient copy) ?
Let me know the details please @stevekrouse :smile:

**Comment by stevekrouse** [comment]
I was thinking that we could have this a "block" in one place in the documentation. Potentially it could go in the More Blocks menu, at the bottom?

You could explain what the comment block is for and put the comment where the code goes so they could copy it easily with the Copy button.

**Comment by stevekrouse** [comment]
https://github.com/stevekrouse/WoofJS/pull/477/files
