### ISSUE TITLE
Changing "Sprites and Backgrounds" to "Images and Backgrounds"

### ISSUE THREAD

**Issue by nicolekelner** [stevekrouse/WoofJS#358]
This is just an idea I had because there is much more than Sprites in this categories. I wonder if there is a more descriptive title for this section.

For example, I see students get stuck finding Circles for Star Catcher.

**Comment by stevekrouse** [comment]
I'm confused. If we changed it to "Images and Backgrounds" I think kids would be more confused because there's more than those things, like shapes and text.

Also, sprite is a scratch word so there's that advantage.

It seems like sprite is a stronger word than image in this context.
