### ISSUE TITLE
Making Tutorials easier to view

### ISSUE THREAD

**Issue by nicolekelner** [stevekrouse/WoofJS#359]
When starting on Woof I think the tutorials tab is not easy to notice. I would love to think of ideas on how to display this in an easier format.

**Comment by stevekrouse** [comment]
What do you think of having it default to open?

**Comment by stevekrouse** [comment]
I agree this is a problem... @nicolekelner do you think it's worth experimenting with leaving it default open for a couple days to see what people think?
