### ISSUE TITLE
Making Image Library easier to navigate 

### ISSUE THREAD

**Issue by nicolekelner** [stevekrouse/WoofJS#360]
I would like to consider changing the layout of the image library that 
![image](https://cloud.githubusercontent.com/assets/6288682/25202241/a81648b4-2522-11e7-947e-0a6d0d3bd5f9.png)
the first section is a button with "Upload your own Image" and then below all of that are the image library. This would reduce the scrolling needed to view sprites. 

I also am curious if it's possible to have just the images visible and when you click on them then the code appears. That might add an extra step not necessary.

**Comment by stevekrouse** [comment]
Yes, the sprite documentation could definitely use some work. We can probably remove much of what you show in the screenshot you included here.

I think the "upload your own image" button is a separate project.

**Comment by Anshuman-Verma** [comment]
@stevekrouse i have an idea, how about having the current 'Images' section named as pre-defined images and we create a separate block there named 'Upload Image' that would reduce the scroll and  would be more detailed and convenient for the users. 
Do let me know if i should fix this, btw nice suggestion @nicolekelner :+1:

**Comment by stevekrouse** [comment]
I think it makes sense to have the button to upload images within the images category as opposed to two image categories, one for pre-defined images and one for uploading.

I think we could remove everything in @nicolekelner's screenshot, from "Create new image:" to "Set location" and replace it with an "Upload image" button. That would definitely reduce scroll.

Potentially, we could use something like https://www.filestack.com/ or continue using firebase, but maybe only for users that are logged in.
