### ISSUE TITLE
Adding an Undo Button

### ISSUE THREAD

**Issue by nicolekelner** [stevekrouse/WoofJS#361]
I see a lot of kids need to undo a mistake but not know the keyboard shortcut for this. It would be great to add a undo button in the nav bar.

**Comment by stevekrouse** [comment]
This seems like it would fit in a traditional Edit menu. We could add a lot of the keyboard shortcuts there, like commenting and uncommenting lines. Also the clean code button can go into this menu.

**Comment by stevekrouse** [comment]
I'm actually really into this idea with the Edit menu. Would love your thoughts @nicolekelner on where it could go. It feels like it should be close to the where you're editing the code, potentially in the Code window tab but I'm not sure what to call this menu. Maybe an icon would do...?

**Comment by stevekrouse** [comment]
Closed in favor of https://github.com/stevekrouse/WoofJS/issues/361
