### ISSUE TITLE
New Images not appearing

### ISSUE THREAD

**Issue by nicolekelner** [stevekrouse/WoofJS#368]
When you put a new image in, it won't appear until you put a second image in after it. It happens in chrome.

**Comment by stevekrouse** [comment]
I'm having trouble reproducing this bug on my chromebook. Could you give me more specific instructions on how to replicate this? For example, which images should I add, in what order, how long should I wait in between, etc?

I have an idea about what *might* be happening... If you have a big image Sprite, it might take a while for it to load. However, when you make any change to your code (like adding a second image), the large original image has already been loaded so it will appear on the screen instantly on the second load.

**Comment by stevekrouse** [comment]
I'm going to close this issue for now. Feel free to reopen it @nicolekelner if it persists for you.
