### ISSUE TITLE
toolTipText addition request

### ISSUE THREAD

**Issue by Anshuman-Verma** [stevekrouse/WoofJS#369]
I think we need several tool tip text for the Preview, Documentation, Code window's buttons on title bar of respective windows, obviously the symbols are self-explainatory but a little addition can make it even convenient, which will be easy for the ones landing on the awesome WoofJS for the first time.
Let me know if we should incorporate this so I start working on it @stevekrouse .

**Comment by stevekrouse** [comment]
I'd be curious what you think the tooltips should say that would make those panes clearer. Either way, adding tooltips never hurt. Give it a go :)

**Comment by Anshuman-Verma** [comment]
Alright ! Thanks, I'll fix this in upcoming PRs. @stevekrouse
