### ISSUE TITLE
Linking students to the broader curricular path on coding.space

### ISSUE THREAD

**Issue by stevekrouse** [stevekrouse/WoofJS#371]
"what is a sprite?" A number of students have asked this over chat. I wonder if we should explain that somewhere...

Or if they don't know what a sprite is, should we take that as knowledge that they don't know Scratch and advise them to learn that first?

**Comment by Anshuman-Verma** [comment]
How about adding a tooltip to the 'Sprites and Backgrounds' button in the documentation block hovering  over which shows the definition of a sprite, they will learn that way if not known to them.
Thoughts @stevekrouse 
Just gimme the precise definition of a sprite and i'll have it added.

**Comment by Anshuman-Verma** [comment]
Do we have an IRC or something where I can contact you quickly & frequently regarding the queries related to woofJS ? If yes, then do email them to me at anshu.av97@gmail.com so then I can discuss the project more often. :raised_hands:

**Comment by Anshuman-Verma** [comment]
Some definition I dug from wiki:-
In computer graphics, a sprite is a two-dimensional bitmap that is integrated into a larger scene. Originally sprites referred to independent objects that are composited together, by hardware, with other elements such as a background.
Do you think the tooltip approach is appropriate for this @stevekrouse

**Comment by stevekrouse** [comment]
Hi @Anshuman-Verma, I'm not sure a tooltip is the right answer here. Let's keep noodling on it...

**Comment by Anshuman-Verma** [comment]
How about we display a link there saying 'What's Sprite?' and if user doesn't know about sprite the user will eventually click and and from there we redirect them to a wiki page about sprites  ?
Does this approach seem appropriate @stevekrouse ?

**Comment by stevekrouse** [comment]
That might work... Where are you thinking this link would go exactly?

**Comment by Anshuman-Verma** [comment]
I was thinking of redirecting the user on the wiki page explaining sprite, do you think that's good enough @stevekrouse 
https://en.wikipedia.org/wiki/Sprite_(computer_graphics)
OR
https://www.merriam-webster.com/dictionary/sprite

**Comment by stevekrouse** [comment]
I don't think either of those links are kid-friendly enough. In my experience kids won't reliably read more than a sentence or two of text -- if that. 

Students not knowing about sprites is really a symptom of the larger problem that they don't know Scratch well enough to be working in WoofJS. So I was thinking it would be cool if we could somehow magically detect that (potentially through the proxy that they don't know about sprites) and recommend in a non-condescending way that they should go back to Scratch projects. Now that I write it out, it seems basically impossible to get this right, but let's keep thinking on it and see if we come up with something clever eventually.
