### ISSUE TITLE
Arrow keys not working in Preview

### ISSUE THREAD

**Issue by nicolekelner** [stevekrouse/WoofJS#374]
I'm using chrome and in my preview, my arrow keys won't map. They work when you pop out the screen though. ![image](https://cloud.githubusercontent.com/assets/6288682/26204308/54d8c2ee-3bac-11e7-81b6-ddd532dddfdb.png)

**Comment by stevekrouse** [comment]
I am not able to reproduce this bug on my computer. Maybe link me to this project so I can try the same exact code you're using?

**Comment by stevekrouse** [comment]
I'm going to close this issue for now. Feel free to reopen it @nicolekelner if it persists for you.
