### ISSUE TITLE
Tools menu

### ISSUE THREAD

**Issue by stevekrouse** [stevekrouse/WoofJS#387]
Currently, we have a few different "Action" buttons: Error, Clean Code, Save. However, I think it would make more sense to aggregate all of these actions (and more) into a "Tools" menu. 

We could include the following actions into this menu:

Copy Ctl-C
Paste Ctl-V
Undo Ctl-Z
Redo Ctl-Shit-Z
Clean Code
Save Ctl-S
Share (gives you a modal with the following things to copy: woofjs.com#hash, woofjs.com/full#hash, and <iframe src=" woofjs.com/full#hash"></iframe>)

**Comment by stevekrouse** [comment]
This would free up the Keyboard shortcuts menu in the documentation, which we can turn into an integrations menu:

* AJAX
* Firebase
* eventually, weather, twitter, other integrations
* eventually, cloud data

**Comment by jwass91** [comment]
How do I get commands like copy and paste to work as buttons?

 Do you think it make sense to leave save, error, and clean code as their own buttons?

 Lastly, I am having trouble because the code editor is going infront of the dropdown menu (see image below).
<img width="466" alt="screen shot 2017-06-19 at 2 56 31 pm" src="https://user-images.githubusercontent.com/8939148/27301383-ff939ae8-5500-11e7-8c9b-96c16f3d233a.png">

**Comment by stevekrouse** [comment]
> How do I get commands like copy and paste to work as buttons?

Good question! That's historically been a pain but I've had success with https://clipboardjs.com/

> Do you think it make sense to leave save, error, and clean code as their own buttons?

I think it makes sense for Save to be its own button for now. Soon we will have autosave so that won't be necessary but let's keep it as a button for now.

Yes, let's keep Error its own button.

I think clean code can go in the Tools menu unless you feel strongly otherwise.

> Lastly, I am having trouble because the code editor is going infront of the dropdown menu (see image below).

That's funny and unexpected! Have you tried messing with the z-index? https://github.com/codemirror/CodeMirror/issues/3770

**Comment by stevekrouse** [comment]
One other comment: This isn't of paramount important, but I think it would be neat if we could give the keyboard shortcut with the specific command key of the system you are on. For apple, that will be the apple key symbol and for everything else it would be the ctl key. 

I already compute this in the code (https://github.com/stevekrouse/WoofJS/blob/master/create.html#L581) so you can use this `ctrl` variable in accomplishing this.

I think the easiest way to go about this will be using VueJS's `{{ }}` syntax. It will look something like:

```html
<li>Copy<span>{{ ctlKey() }}-C</li>
```

Where you defined `cltKey()` as a method that returns the proper key here:

https://github.com/stevekrouse/WoofJS/blob/master/create.html#L400

(As a side note: you're probably going to need to define every method you use in this Tools menu in that VueJS methods object so you can use it in the HTML as `@click=method()` https://vuejs.org/v2/guide/events.html#Method-Event-Handlers. Another side note: `@click` is the VueJS way of adding `onclick` handlers. It is equivalent to `v-on`.)

**Comment by stevekrouse** [comment]
![screenshot 2017-06-20 at 6 10 20 pm](https://user-images.githubusercontent.com/2288939/27358256-bea8f882-55e3-11e7-9208-6b1c6f480eea.png)

**Comment by stevekrouse** [comment]
https://github.com/stevekrouse/WoofJS/issues/393
