### ISSUE TITLE
Make a block for sprite.showing

### ISSUE THREAD

**Issue by madduccino** [stevekrouse/WoofJS#394]
I use this a lot and I can't find it in the docs. Also I've noticed students try to write something like this in lieu of it: 
if (sprite.show())

**Comment by stevekrouse** [comment]
Huh, that's a little surprising to me -- that there'd be such a use case for this, but I guess it makes sense. Do you think it belong in the Looks menu near `sprite1.show()` or in the Sensing menu?

**Comment by madduccino** [comment]
I think it belongs in the looks menu.
