### ISSUE TITLE
Line angle is off by 90 degrees

### ISSUE THREAD

**Issue by joebeachjoebeach** [stevekrouse/WoofJS#395]
Example here: http://woofjs.com/create.html#line-test

I think the rectangle and the line should be oriented the same way, but they're off by 90 degrees.

@madduccino I know you worked on `Line()` recently; can you point me in the right direction?

**Comment by joebeachjoebeach** [comment]
Oh, also, I noticed `Line()`s have a `height` property, but do you think we should call it `length` instead?

**Comment by stevekrouse** [comment]
Good idea, length makes more sense than height for lines

**Comment by joebeachjoebeach** [comment]
OK, I'm figuring it out but still working on it. It's because, for a rectangle, `width` refers to the x dimension and `height` refers to the y dimension, but it's essentially the reverse for the line. So I'm just going to swap them then add a property `length` which will basically point to `width`

**Comment by madduccino** [comment]
Sounds good Joe!

**Comment by madduccino** [comment]
I wonder if it has something to do with the way I rotated the rectangle?

**Comment by madduccino** [comment]
Also will your solution affect the line's collision detection? https://github.com/stevekrouse/WoofJS/blob/master/src/woof.es6.js#L629

**Comment by joebeachjoebeach** [comment]
I'll make sure it doesn't mess with collision. Thanks for pointing it out!

Yeah, I think the way the line is made is basically a 90-degree rotation from the way the rectangles are made, but it shouldn't be a tough fix. I'll just have to make sure it doesn't interfere with anything else
