### ISSUE TITLE
Native Say and Think implementations

### ISSUE THREAD

**Issue by jwass91** [stevekrouse/WoofJS#398]
Scratch offers the simple `Say` and `Think` functions that make it easy for students add text to their games. WoofJS currently doesn't have these functions, and even though they could be mimicked by a student with `Text` and `Image` sprites, it would take a lot of code. Should this be built into Woof?

**Comment by stevekrouse** [comment]
Could you link to a woofjs.com game link where you implement them? I'd be curious to see how much code it would take to make them.

**Comment by stevekrouse** [comment]
I agree that it would be cool to have `sprite.say("hello")` or `sprite.think("something")`
