### ISSUE TITLE
Built-in math functions

### ISSUE THREAD

**Issue by jwass91** [stevekrouse/WoofJS#399]
Currently functions like sqrt, floor, abs, sin, etc. aren't available in Woof. Students can use the javascript `Math.function()` code, but it would be easier if they were built into Woof. So you could to `abs(-9)` instead of `Math.abs(-9)`. Also the javascript trig functions are for radians but it would make more sense if Woof offered these functions for degrees. Most students probably don't know about Radians nor how to convert between degrees and radians. 

These should be pretty easy to implement.

**Comment by stevekrouse** [comment]
Yeah, I guess this couldn't hurt. I definitely like the idea of trig functions that are based off degrees and not radians (although I bet that students who know about trig functions well enough to use them probably also know how to convert from degrees to radians)
