### ISSUE TITLE
overlap, over, mouseOver, and mouseDown don't work when rotated

### ISSUE THREAD

**Issue by stevekrouse** [stevekrouse/WoofJS#400]
Apparently I forgot about these methods when I added the collider code that allows shapes to detect collisions when rotated. Potentially the simplest way to solve these is by constructing a simple circular collider of radius 1 pixel at the x and y coordinates and then check if they are touching.

The relevant methods are defined at this line and below:

https://github.com/stevekrouse/WoofJS/blob/master/src/woof.es6.js#L810

**Comment by hallpell** [comment]
This appears to be fixed, and the relevant collider code (which I believe is responsible for the mentioned functions) does handle rotated sprites.
