### ISSUE TITLE
better error message for setting image URL to ""

### ISSUE THREAD

**Issue by stevekrouse** [stevekrouse/WoofJS#424]
http://woofjs.com/create.html#LK2/25

Error on line 10: `setBackdropURL("")`

The problem is that I search for the broken image url by its value, which in this case is the empty string so matches in the beginning of the code. Also makes the error message confusing because there's nothing after the colon.

Pull request: https://github.com/stevekrouse/WoofJS/pull/503

**Comment by stevekrouse** [comment]
As you can see [here](https://github.com/stevekrouse/WoofJS/commit/af237425cca5db4de2adec53a70e34c2d0fec459#diff-b6526a06bd2c9aea58ea7ea1f53f18f8R670) I compute the line number that an image error happens by searching for the URL text in the code. 

So you'll need to somehow handle this special case where the URL provided is the empty string, potentially by making the `lineno` property `undefined`.

You'll also want to create a more specific error message, like "you provided an empty text as the url for an image. Please provide a valid link to an image."

**Comment by truthgoddess** [comment]
@stevekrouse @gmarraro See #559 Thanks @gmarraro for your initial work on this.

**Comment by stevekrouse** [comment]
Closed https://github.com/stevekrouse/WoofJS/pull/561
