### ISSUE TITLE
Turn the keyword 'woofjs' or 'woofjs.com' to hyperlinks

### ISSUE THREAD

**Issue by Anshuman-Verma** [stevekrouse/WoofJS#441]
I saw a lot of instances of the words 'woofjs' or 'woofjs.com', will it be good if we convert them all to hyperlinks clicking over which they will be redirected to [woofjs](https://woofjs.com).
Just a suggestion so let me know your views.

**Comment by stevekrouse** [comment]
You mean in the readme?

**Comment by Anshuman-Verma** [comment]
Yes, will that be any good ?

**Comment by stevekrouse** [comment]
I think turning all woofjs.com text into links is a great idea. I don't think you need to do that for all references to WoofJS itself.

**Comment by Anshuman-Verma** [comment]
Had such thoughts, it's better to leave WoofJS as is, will change instances of [woofjs.com](https://woofjs.com)
