### ISSUE TITLE
Add more hyperlinks

### ISSUE THREAD

**Issue by Anshuman-Verma** [stevekrouse/WoofJS#445]
> The documentation that you find on woofjs.com/create is contained within the docs/ folder.

This line in readme can be improved by providing them the links to respective items and using this people can redirect themselves to the docs at ease.

Changed view will look something like this
The documentation that you find on [woofjs.com/create.html](https://woofjs.com/create.html) is contained within the [docs/](https://github.com/stevekrouse/WoofJS/tree/master/docs) folder.

Views @stevekrouse ?

**Comment by stevekrouse** [comment]
Great idea - go for it!

**Comment by Anshuman-Verma** [comment]
Thanks for the approval, on it !
