### ISSUE TITLE
Migrate/update old users

### ISSUE THREAD

**Issue by jwass91** [stevekrouse/WoofJS#455]
With the new sign up that requires a unique username and the option to receive the newsletter, all old users need to be updated. 

- Whenever a user logs in we will check if they are "new" or "old"
- To check if a user is "old" we just need to see if the newsletter field exists for them
- Then if they are an "old" user we will direct them to some sort of forms that requires them to choose a new username (or possibly keep their old one) and check off if they want to receive the newsletter
-  Then we will update the users info and add their new username to the unique username list

**Comment by stevekrouse** [comment]
Sounds like a great plan!
