### ISSUE TITLE
Project Organisation

### ISSUE THREAD

**Issue by Anshuman-Verma** [stevekrouse/WoofJS#457]
I've seen some css written in all the html files, how about we move all html files in a separate `html` folder and all the css in them in a separate `css` folder by creating respective css files for all html pages to make the project clean and convenient.
Though we can leave `index.html` to live in the project directory but i think other html files should be moved to a separate folder.
views @stevekrouse ?

**Comment by stevekrouse** [comment]
Hi @Anshuman-Verma - I appreciate these ideas!

We're going to keep the organization the same for now for a few reasons:

* I personally believe keeping HTML, CSS, and JS all in the same page is easier for new developers to get a sense of how the project works. Want to know how `/create.html` works? Simply look at that one file.

* Moving the other files to folders will mess with the URL schemes, given how Github pages works.

**Comment by Anshuman-Verma** [comment]
Makes sense, the reason i got accustomed well with woof was due to the in file css and scripts which explains stuff in place so no need for excessive browsing or stuff to find the linked files.
Surely this practice helps developers get a kickstart with woofjs
Thanks for the views @stevekrouse !
