### ISSUE TITLE
recommend that desktop users switch to chrome

### ISSUE THREAD

**Issue by stevekrouse** [stevekrouse/WoofJS#465]
Or we could fix the safari bugs...

**Comment by stevekrouse** [comment]
There's a huge bug in firefox, making woof basically unusable. Getting this feature implemented is top-priority!

**Comment by stevekrouse** [comment]
@leesan11 maybe try your hand on this one? The problem is that given our small team, we can only make sure Woof works on Chrome. However, we don't tell users that Safari and Firefox are unsupported so they run into bugs and get annoyed. The solution is to detect the user's browser and if it's not Chrome, we alert them with a popup (or something) that tells them that they should consider using chrome.

**Comment by leesan11** [comment]
@stevekrouse Sure thing!

**Comment by leesan11** [comment]
@stevekrouse Should the notification popup after they click (start coding on woofjs.com)?
