### ISSUE TITLE
fullscreen button should open saving prompt

### ISSUE THREAD

**Issue by stevekrouse** [stevekrouse/WoofJS#467]
Clara Ekenberg:

> Hi, this is a idea I've got: could´t you make the full screen button both Save and make Full screen? It's irritating to first hit the Full screen button and then be reminded that I should hit the Save button first, hit the Save button and then  - finally - hit the full screen button.

**Comment by stevekrouse** [comment]
Relevant places in the code:

* https://github.com/stevekrouse/WoofJS/blob/master/create.html#L466
* https://github.com/stevekrouse/WoofJS/blob/master/create.html#L1125
* https://github.com/stevekrouse/WoofJS/blob/master/create.html#L1196
* https://github.com/stevekrouse/WoofJS/blob/master/create.html#L1209

**Comment by leesan11** [comment]
@stevekrouse Hello! I am new to open source. Would you mind, if I try resolving this issue? I was curious about this issue, so I already created a working edit that opens the save modal on popout() click, and opens the full screen window after save. Unfortunately, I feel that my edit is inefficient and messy. I would love your feedback on my edit if you allow me to try a PR.

**Comment by stevekrouse** [comment]
Appreciate it! Yeah go ahead and submit a pull req from your fork. (I don't think you neee my permission for that.) Let me know if you have any trouble

**Comment by stevekrouse** [comment]
Also, this is the advice I gave to the last person to try this issue https://github.com/stevekrouse/WoofJS/pull/502#issuecomment-339392297

**Comment by leesan11** [comment]
Thank you so much! I just did a pr!
