### ISSUE TITLE
Polygon doesn't recognize onMouseDown 

### ISSUE THREAD

**Issue by madduccino** [stevekrouse/WoofJS#469]
http://woofjs.com/create.html#poly-test

**Comment by stevekrouse** [comment]
Looks like someone finally found this bug!

> Hello,
>
> Is is possible to make a polygon sprite  clickable? I created a triangle sprite(i.e var arrow), but onMouseDown function(arrow.onMouseDown) did not work.  
>
> When I used the same function for a rectangle sprite, it worked. 
>
> Is there any way?
>
> Thank you.
