### ISSUE TITLE
Non-global mode instrux in readme

### ISSUE THREAD

**Issue by madduccino** [stevekrouse/WoofJS#470]
@joebeachjoebeach - I think you worked on the readme for Woof. I was curious about operating Woof in non-global mode and followed these instructions:

`var project = new Woof({global: false, width: 300, height: 400})`
`var IMAGE_NAME = new Woof.Image({project: project, url: "./images/SMJjVCL.png"})`

By doing this: 

`var muffin = new Woof({global: false, width: 300, height: 400})`
`new Woof.Image({project: muffin, url: "http://bit.ly/2uMsB40"})`

But I couldn't get it to work until I changed the second line to:

`new muffin.Image({project: muffin, url: "http://bit.ly/2uMsB40"})`

So I'm wondering if the instructions in the readme should instead say:

`var project = new Woof({global: false, width: 300, height: 400})`

`var IMAGE_NAME = new **project**.Image({project: project, url: "./images/SMJjVCL.png"})`

**Comment by joebeachjoebeach** [comment]
That's really interesting. I did do some work on the readme, but I didn't contribute that bit.

I tried messing around with non-global mode recently and failed to do so, but now I think I understand why. I actually meant to ask about it. I'm guessing @stevekrouse can provide some insight.

**Comment by stevekrouse** [comment]
I agree @madduccino that the readme should be updated. It could now say:

```javascript
var project = new Woof({global: false, width: 300, height: 400})
var IMAGE_NAME = new project.Image({project: project, url: "./images/SMJjVCL.png"})
```
