### ISSUE TITLE
version woof to commit hash and save on specific projects

### ISSUE THREAD

**Issue by stevekrouse** [stevekrouse/WoofJS#471]
One way to increase the rate we are able to update the Woof API is to version it. I personally am enticed by the idea of each new commit hash to Woof being treated as its own version. Then we don't have to waste a single second on semantic versioning discussions.

Whenever a user creates a new project we will save in the database the version of the woof library *and* the documentation. Then every time they go to edit that project, we give them that version of both.

However, I think we will find that sometimes students will want to upgrade their project to a newer version of Woof so we may have to have a dropdown that lets you select a version from between the version your project was created at, the most recent version, and the ability to type in another version.

**Comment by hallpell** [comment]
My current thoughts on this are that Woof is established enough that any changes we make will need to maintain backwards compatibility, and updates are intended to improve functionality enough that we'd like students to automatically be moved to new versions. I like this as an idea but I don't think it removes enough constraints on future updates to be worth implementing.
