### ISSUE TITLE
Allow same-name projects to exist for different users

### ISSUE THREAD

**Issue by madduccino** [stevekrouse/WoofJS#478]
It would be great if we could use "account->project" as the unique identifier for projects so that users with different accounts can name their project the same thing.

**Comment by stevekrouse** [comment]
This is a great idea that I've thought about before. https://github.com/stevekrouse/WoofJS/issues/233 and decided against it.

It's also been requested a number of times.

There are pros and cons on either side, and I'm truly ambivalent about it. If I had to build Woof over again, I'd probably do it in the way you're suggesting here, but given that it's already the way it is and the pros/cons of switching that I'm aware of in my head don't provide a super compelling case for switching, we might as well stick with what we have cause it's free.

I don't have time to go into it now but if you wanted to start compiling the list of pros and cons on this issue @madduccino, that'd be great. I'd be open to be convinced here.

One thing we'd have to thing through here is how to migrate existing projects and whether old URLs would break or if we could somehow migrate them seamlessly.
