### ISSUE TITLE
Incorrect highlight of line containing error

### ISSUE THREAD

**Issue by gmarraro** [stevekrouse/WoofJS#504]
As you can see, line 1 is highlighted as having an error, when the actual error is on line 10, because of the empty string. I'm wondering why it's incorrectly identifying which line the error is on here?

<img width="472" alt="screen shot 2017-10-11 at 11 32 08 am" src="https://user-images.githubusercontent.com/29807549/31510823-b029c83a-af53-11e7-86dc-06d0f368baed.png">

**Comment by stevekrouse** [comment]
Good question... I think it makes sense to solve this problem over here https://github.com/stevekrouse/WoofJS/issues/424
