### ISSUE TITLE
Change error messages to recognize a miscapitalized function and provide the correctly capitalized alternative.

### ISSUE THREAD

**Issue by MMarki** [stevekrouse/WoofJS#508]
Currently, Woof can detect when a variable name has been misspelled and suggest the correct spelling in an error message. If the student clicks on the suggested variable name, it finds the misspelled variable name and replaces it with the suggested name. It would be great to leverage this suggestion/replacement functionality to allow the same thing to work for miscapitalized functions, since it's something that so many students struggle with.

Example: "turnLEFT" should be detected and "turnLeft" would be suggested as an alternative.

**Comment by stevekrouse** [comment]
Great idea! I wonder if we could do this by lowercasing all inputs to [this equation](https://github.com/stevekrouse/WoofJS/blob/master/create.html#L749) to detect if the only thing between the error code and the "correct version" is capitalization. @madduccino thoughts?

**Comment by madduccino** [comment]
That should work! I'll work on this.

**Comment by truthgoddess** [comment]
@madduccino @stevekrouse I've a feeling we should close this issue. Maddy or someone else seems to have done a pretty good job addressing this. It's not perfect, but Woof seems to handle most capitalization errors pretty well for function. 

I'd close it myself, but still feeling that I should check with you both. If you think it is ok for me to close issues, then let me know. I can type why I think it should be closed, and then you can look at the most recent closed issues at your leisure.

**Comment by truthgoddess** [comment]
Closed because it has been implemented well enough already. If we want to open this again in the future, it'll be more optimizing it. I feel there are more important issues to work on right now.
