### ISSUE TITLE
Change the content of the default conditional statements so that they do not trigger an error when pasted into the editor.

### ISSUE THREAD

**Issue by MMarki** [stevekrouse/WoofJS#511]
Currently, conditional statements in Woof contain the text "/* condition */" inside their parentheses. This triggers a syntax error when pasted into the editor because JavaScript reads this as an empty conditional. I've seen a lot of students get anxious, worried, or annoyed when they paste in the default code and get an error message. Usually, they think they've done something wrong and they don't understand what has happened.

One possible solution would be to have a conditional statement like "1===1" instead. This would not trigger an error, and could lead to a valuable discussion with a student about booleans. The downside is that this portion of the statement is no longer explicitly labeled as a conditional.

**Comment by stevekrouse** [comment]
This is a great idea! Maybe we do a more helpful/relevant default condition:

```javascript
if (mouseDown) {
  /* then do stuff here */
}
```

We could also update the picture of this block to have the mouseDown scratch block in the if-block in the documentation.

I'm not sure if I like this idea, but we could do both if we wanted...

```javascript
if(mouseDown /* replace in between the parenthesis with our own condition */) {
  /* then do stuff here */
}
```
