### ISSUE TITLE
New Tutorials

### ISSUE THREAD

**Issue by Beauvelop** [stevekrouse/WoofJS#514]
Dear Steve, I teach js & python at a school in CT & I want to send my congrats to you and sincere thanks for all of your efforts. woof.js is outstanding.

Would you be averse to additional tutorials?

I'm working on projects to supplement the built-in tutorials and here is a WIP example:
https://docs.google.com/presentation/d/17XJ0fddtuxYRFFglBwHP-va-xjmfpGvAfBcCNued68c/edit?usp=sharing
I hope that link works.

As I create new projects for my students I hope to add additional supplementary materials together. I'm considering hosting a site, but thought I might run the idea by you to see if there was something I might be involved in to enhance the built-in woofjs exercises.

Anyway.. Best of luck to you,

Sincerely, Beau Jackson
feel free to DM me directly @beau_dev

**Comment by stevekrouse** [comment]
Hello @Beauvelop! Thanks for your kind words, and for teaching WoofJS -- makes my night to hear about!

I don't have time now to properly review and give comments on your proposal, but I just wanted to say thank you for writing and that my curiosity is piqued! I'll get back to you in the next few days with more specific notes and next steps.

**Comment by stevekrouse** [comment]
Hi @Beauvelop - just looked through your slides. Very fun! 

If you host these tutorials somewhere, I'd love to link to them in our [Teacher Guide](http://woofjs.com/guide). There are a few other tutorials I link to there.

Our curricular style is particularly unique. Here's how I describe it in our [Educational Philosophy](http://www.thecodingspace.com/philosophy):

![screenshot 2017-11-08 at 2 50 32 pm](https://user-images.githubusercontent.com/2288939/32571064-30165a0e-c494-11e7-8755-427cc6cc1097.png)

**Comment by Beauvelop** [comment]
Outstanding. Working on this all the time. Once I have some completed packages/code/hosting and a site to deliver it all, I'll be in touch.

Best,

Beau
