### ISSUE TITLE
Enable HTTPS/SSL security

### ISSUE THREAD

**Issue by otech47** [stevekrouse/WoofJS#515]
Currently hosted on Github Pages, which makes it difficult to enable SSL for custom domains

**Comment by stevekrouse** [comment]
This seems like a reasonable way to do it: https://hackernoon.com/set-up-ssl-on-github-pages-with-custom-domains-for-free-a576bdf51bc

**Comment by stevekrouse** [comment]
Note from 7th grade teacher about this:

> my students (ever vigilant in their digital citizenship) noted that Chrome says that your website is not secure

**Comment by otech47** [comment]
Been poking at this trying to get it to work with one another domain+repo with Github Pages enabled but still not 100% there. I'll update later after testing/waiting for DNS settings propagate
