### ISSUE TITLE
Clone tutorial missing comma after minX on step 2

### ISSUE THREAD

**Issue by madduccino** [stevekrouse/WoofJS#517]
![screen shot 2017-11-13 at 12 52 29 pm](https://user-images.githubusercontent.com/2099441/32739968-6f7f3092-c86f-11e7-9c96-414581e92dc0.png)

**Comment by truthgoddess** [comment]
@stevekrouse @madduccino This seems to have already been fixed. I'll be sure to check to see if the error is still there before I start working on it. ;p

**Comment by stevekrouse** [comment]
Indeed, closed https://github.com/madduccino/coding.space/pull/114
