### ISSUE TITLE
Scrolling bar on tutorials doesn't work

### ISSUE THREAD

**Issue by nicolekelner** [stevekrouse/WoofJS#518]
![screenshot 2018-01-10 at 10 41 58 am](https://user-images.githubusercontent.com/6288682/34781089-ea5afc6e-f5f2-11e7-9324-d27497d0d996.png)

The sub-scrolling bars on untutorials are frozen and don't work. I think they should be removed so the master scroll bar is the only option.

**Comment by stevekrouse** [comment]
This is just a design thing and not a scrollbar
