### ISSUE TITLE
Global height and width variables changeable by users

### ISSUE THREAD

**Issue by the-viking** [stevekrouse/WoofJS#534]
You can access and change the height and width variables. If you change one of these it messes up the coordinate system. This could be confusing especially if you're trying to change the width or height of a sprite and leave of the name or something

**Comment by stevekrouse** [comment]
Wow great catch - this is a terrible bug! We want `width` and `height` to be readable but not writeable. They should throw an error if you try to write to them.

I imagine we'll accomplish this behavior with the `defineProperty` syntax, [used here for example](https://github.com/stevekrouse/WoofJS/blob/65734178f5d84efbbbcf614a4e753997d2f96a42/src/woof.es6.js#L37), where we allow reads, but throw errors on writes. 

We'll just have to make sure that we can actually set those variables [in this one place here](https://github.com/stevekrouse/WoofJS/blob/65734178f5d84efbbbcf614a4e753997d2f96a42/src/woof.es6.js#L155) without throwing an exception.

I imagine these aren't the only two global variables we want to protect from being written to...

**Comment by truthgoddess** [comment]
@stevekrouse Your thoughts would help me here.

Since `width` and `height` variables are what set the size of the canvas to the current size of the window, and it changes depending upon the menus that the user has open, I'm not sure how to make it not allow writes. That is, it writes the new width and height based upon the window each time it renders, doesn't it?

If I'm wrong, any quick thoughts you have about 'how' or 'where' to do this would help me move forward with this issue!

**Comment by stevekrouse** [comment]
Good question. This might require a conversation... You are correct that we want `width` and `height` to change in response to resizings, but in a way that the *programmer* can only read. The library itself can *internally* write to those values (indeed it must), but the user should not be able to write `width = 200` and have it take effect. JavaScript has this thing called `defineProperty` which lets you specify what you want to happen when someone tries to either read or write to a property.

I use it [here](https://github.com/stevekrouse/WoofJS/blob/65734178f5d84efbbbcf614a4e753997d2f96a42/src/woof.es6.js#L37) to hook into the updating of the `cameraX` (an abstraction we haven't really exposed to our students). We have a *private variable* (vs a *public variable*, these terms are google-able) of `_cameraX` that actually holds the value. The `cameraX` term is the shell on top. We need to do the same with `width` and `height`: have a `_width` and `_height`.

Google around and read the example I mentioned and maybe we can chat if you are still stuck :)

**Comment by truthgoddess** [comment]
Great. I'll definitely use your help to figure this out and reach out for a chat if I can't. I probably need to wait until I have a bit more time in a work session, but hopefully in the near future, I'll hear about that and can devote a lot more time to it.
