### ISSUE TITLE
Jokes from Chuck Norris API innapropriate?

### ISSUE THREAD

**Issue by the-viking** [stevekrouse/WoofJS#537]
Some of the jokes are inappropriate for students. One I just got was ["Chuck Norris fucking haxxored your mom's ass last night."](https://api.chucknorris.io/jokes/ftV4qIlNTWWQKbDl8HCo2Q) (??). Maybe there's a better joke API we could incorporate instead? I just found [this list](https://www.programmableweb.com/category/humor/api). There are a few that could work; maybe [this one](https://www.programmableweb.com/api/webknox-jokes), although I've yet to try it.

**Comment by stevekrouse** [comment]
Yikes, that's a terrible joke! I'm all for removing this joke library as a first step. Should be a relatively simple pull request

**Comment by ruffle1986** [comment]
Who's working on this?

**Comment by stevekrouse** [comment]
I dont think anybody yet. Would you like to give it a go?

**Comment by ruffle1986** [comment]
How would you like to solve it? Removing the CN integration completely?

**Comment by stevekrouse** [comment]
I think that'd be a great first step
