### ISSUE TITLE
Repeat allows non integer values

### ISSUE THREAD

**Issue by rsimari** [stevekrouse/WoofJS#542]
Not sure if this is intentional or not but the repeat block code allows a non integer value such as:
```
var x = 0
repeat(101 / 10, () => { x++ })
// x = 11
```
I understand that Woof.prototype.Repeat at [src/woof.es6.js#1395](https://github.com/stevekrouse/WoofJS/blob/2c11757784bcba0cb8e27b7582078d091cdec5bb/src/woof.es6.js#L1394) just subtracts one for every iteration and ends when the count drops to or below 0. 

However, it is a little hard to explain to a beginner why the result is it running 11 times and not 10.1 times since its not running the loop 0.1 times (1/10th of the loop)

**Comment by stevekrouse** [comment]
Great point! Do you think it should throw and error or repeat 10 times (take the floor of the input)?

**Comment by rsimari** [comment]
I think that it should run 10 times and possibly provide a warning clarifying that the loop can only run a whole number of times.

**Comment by stevekrouse** [comment]
Agreed, I think a simple Math.floor would suffice. We currently don’t have a mechanism for warnings (that aren’t errors) so we can do without for now. Want to take a crack at implementing in a pull request?

**Comment by rsimari** [comment]
Sounds good. Sure I'll submit the pull request
