### ISSUE TITLE
Circle - Line collision detection

### ISSUE THREAD

**Issue by rsimari** [stevekrouse/WoofJS#544]
Right now the docs recommend using distanceTo(sprite) for circles, but if you use distanceTo for collisions with a line it does not work as intended. The collision is only detected if the circle comes the specified distance from the (x,y) point, but the Line is comprised of (x,y) and (x1,y1). 

Here is some code the recreates what I'm referring to:
```
var lineSprite1 = new Line({color: "pink", 
  width: 10, 
  x: -100, 
  y: 100, 
  x1: 10, 
  y1: 20
})

var circleSprite = new Circle({
  radius: 10, 
  color: "#444444", 
  x: 0, 
  y: 0
})

forever(() => {
  if (keysDown.includes('UP')) {
    circleSprite.y++;
  } else if (keysDown.includes('DOWN')) {
    circleSprite.y--;
  } else if (keysDown.includes('LEFT')) {
    circleSprite.x--;
  } else if (keysDown.includes('RIGHT')) {
    circleSprite.x++;
  }
  
  if (circleSprite.distanceTo(lineSprite1) < 10) {
    circleSprite.color = 'red'
  } else {
    circleSprite.color = '#444444'
  }
})
```

While using touching() does work, as the docs say it is not as precise at the distanceTo(sprite) function should be.

**Comment by rsimari** [comment]
at [src/woof.es6.js#711](https://github.com/stevekrouse/WoofJS/blob/2c11757784bcba0cb8e27b7582078d091cdec5bb/src/woof.es6.js#L711) you can see only .x and .y are used in finding the distance to the sprite when we should consider the entire polygon

**Comment by stevekrouse** [comment]
Good points. As discussed on pull request https://github.com/stevekrouse/WoofJS/pull/538, I think the ultimate solution is to have more accurate colliders for all the shapes (lines would be be converted to rectangles for their colliders) and they just use the SAT methods to determine collisions: http://jriecken.github.io/sat-js/#collision-tests

**Comment by truthgoddess** [comment]
@stevekrouse @madduccino It looks like the touching only has trouble with collision detection for circle sprites and images. See https://woofjs.com/create.html#Circlespritetouchingtest

So students trying to create collision detection between image sprites might be seeing this problem. I'm going to create a simple branch to change the text that says:
 "For circular sprites, distanceTo() will be more accurate than touching()."
 to:
"
"For some sprites, distanceTo() will be more accurate than touching()."

I believe that will help clarify things. Then I believe we can close this issue. Other collision detection development work can be done elsewhere.
