### ISSUE TITLE
Changing width and height of oval sprite doesn't work

### ISSUE THREAD

**Issue by the-viking** [stevekrouse/WoofJS#545]
The size of oval sprites can't be set (except for in the constructor). This code should change the oval's size when the stage is clicked, but doesn't do anything:

```javascript
var ovalSprite1 = new Oval({
  width: 200, 
  height: 552, 
  color: "green"
})

onMouseDown(() => {
  ovalSprite1.width = 20
  ovalSprite1.height = 20
})
```

[Test project showing the bug](http://woofjs.com/create#oval-test)

**Comment by stevekrouse** [comment]
Thanks @the-viking! It was a quick fix
