### ISSUE TITLE
when's stop working in large project

### ISSUE THREAD

**Issue by stevekrouse** [stevekrouse/WoofJS#546]
http://woofjs.com/create.html#Name-that-tune/303

**Comment by irinbanerjee** [comment]
Can you please explain what the issue is? I am a beginner and I want to learn  :)

**Comment by irinbanerjee** [comment]
Can you please explain what the issue is? I am a beginner and I want to learn  :)

**Comment by stevekrouse** [comment]
This one is a bit complicated. Maybe start with an easier first issue? https://github.com/stevekrouse/WoofJS/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22
