### ISSUE TITLE
Changing passwords in Woof

### ISSUE THREAD

**Issue by the-viking** [stevekrouse/WoofJS#550]
There is currently no way to change a password (besides clicking "Forgot my password" to reset it), which seems like a security issue

**Comment by stevekrouse** [comment]
Do you mean a security issue in the sense that someone might be able to access another person's account? Or in the sense that someone might not be able to access their own account?

There probably should be a way for a user to see all their old projects without having to log in (as all projects are public if you know their name) in the case where they can't access the email address they signed up with, so they can copy their old projects to a new account.

**Comment by the-viking** [comment]
I meant that someone could access another person's account, and change the code or something (although I guess then they could still restore to an older version). Might not be a big issue yet, though I imagine it could come up. I've been making student accounts for multiple classes all with the same password and was looking for a way for students to be able to change their passwords in the account settings.

**Comment by stevekrouse** [comment]
Interesting... I guess the security issue then is that you're making all the passwords the same. What email address are you using for those accounts?

Another scheme you could try: use different passwords for each student and keep track of them in a google spreadsheet that only teachers have access to (for when students forget)
