### ISSUE TITLE
Tab when selection highlighted deleting code

### ISSUE THREAD

**Issue by truthgoddess** [stevekrouse/WoofJS#562]
When a user highlights text and presses tab, the code is deleted.

I believe the block selected should indent, as other code editors do.

**Comment by stevekrouse** [comment]
Yesssss! Top priority!

**Comment by truthgoddess** [comment]
Took a look to see if I could fix this in a few minutes. Seems like we already have this code in codemirror.js.

```
defaultTab: function(cm) {
      if (cm.somethingSelected()) cm.indentSelection("add");
      else cm.execCommand("insertTab");
    },
```

Not going to work on this this minute, so thought I'd say, if anyone has a brilliant idea of why that isn't working already, comment below. :)
