### ISSUE TITLE
Email Address Invalid

### ISSUE THREAD

**Issue by willWashington** [stevekrouse/WoofJS#573]
It appears that Steve's email address is no longer valid, yet it is referenced in the documentation:

![image](https://user-images.githubusercontent.com/22458888/62595361-105e1e00-b8ac-11e9-9284-b684b50d04f7.png)

![image](https://user-images.githubusercontent.com/22458888/62595401-35529100-b8ac-11e9-83a7-2565cd842f8f.png)

Maybe I'm missing something, but I feel like I got this one right.

I'll be happy to make fixing this my first contribution if someone would be so kind as to provide Steve's working email address or an official contact address for this project. :)

**Comment by stevekrouse** [comment]
Nice catch! I'll update it...
