### ISSUE TITLE
Improvements to the wrapper to the Audio interface

### ISSUE THREAD

**Issue by johnbujalski** [stevekrouse/WoofJS#580]
There should be a way to detect whether a particular Sound is playing, and its current timestamp.

There should be a way to start a Sound over when playing it - currently startPlaying() always "resumes" looping audio.

stopPlaying() and pausePlaying() should do different things - stopPlaying() should revert the timestamp to 0, whereas pausePlaying() maintains the current timestamp.

**Comment by hallpell** [comment]
Added all this plus duration. Makes stuff like:
https://woofjs.com/create.html#hallpell_sound_pausing
possible.
