### ISSUE TITLE
Custom Audio

### ISSUE THREAD

**Issue by JakeGoldmanCode** [stevekrouse/WoofJS#595]
How do I get a custom audio, because from my website i use my url to mp3, then when i do start playing i dont hear anything???

what do i do

**Comment by hallpell** [comment]
Our audio capabilities are definitely a bit rough around the edges. I put together a [brief example](https://woofjs.com/create.html#hallpell_audio_example/3) for you, showing an example of a functional sound object in Woof using an external URL. A number of external URLs seem not to work for reasons I'm not easily able to figure out. The HTML audio tag seems to have some issues loading various URLs, though I can't nail down exactly why. Inspecting the page and looking at the console for errors loading the Audio element will give you clues to try tracking down, but ultimately the main solution is to just find another .mp3 hosted on a site that seems to work.

**Comment by JakeGoldmanCode** [comment]
thanks im gonna try using github as a host this time
