### ISSUE TITLE
sprites still there after delete

### ISSUE THREAD

**Issue by sallymatson** [stevekrouse/WoofJS#86]

**Comment by stevekrouse** [comment]
We actually can't remove sprites from memory (especially if there are running forevers that still reference them).

The easy make-shift solution is that we have to be diligent in all sprite / project methods that we need to first check if `project.sprites.includes(this)` before returning things.

Potentially, we could have sprite.forevers that delete when the sprites do (so we don't have memory leaks), but this feels unnecessary for now.
